language: objective-c
osx_image: xcode8.3
xcode_project: GSMarkupParser.xcodeproj
matrix:
  include:
    - xcode_scheme: GSMarkupParserDemo_iOS
      xcode_sdk: iphonesimulator10.3
    - xcode_scheme: GSMarkupParserDemo_macOS
      xcode_sdk: macosx10.12
