language: objective-c
osx_image: xcode8.3
script:
  - xcodebuild clean && xcodebuild build \
    -project GSMarkupParser.xcodeproj \
    -scheme GSMarkupParserDemo_macOS \
    TEST_AFTER_BUILD=YES \
    ONLY_ACTIVE_ARCH=NO \
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES \
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
